services:
  db:
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-somestrongpassword}
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=${MYSQL_USER:-wordpressuser}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-wordpresspassword}
    ports:
      - 33061:3306
  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    volumes:
      - ./wordpress:/var/www/html
    ports:
      - 8081:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=${MYSQL_USER:-wordpressuser}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD:-wordpresspassword}
      - WORDPRESS_DB_NAME=wordpress
  aapanel:
    image: aapanel/aapanel:fresh
    volumes:
      - ./wordpress:/www/wwwroot
    ports:
      - 8886:7800
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-somestrongpassword}
      - PMA_HOST=db
    ports:
      - 8887:80
volumes:
  db_data:
  wp_data:
  website_data: